### ISSUE TITLE
FDP throws a nullPointerException for ApacheAnt170

### ISSUE THREAD

**Issue by gagansodhi10** [Karthikc2608/SoftwareMeasurement#18]
FDP throws a nullPointerException for ApacheAnt170

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.NullPointerException
	at gr.uom.java.ast.metrics.FDP.computeLaa(FDP.java:46)
	at gr.uom.java.ast.metrics.FDP.<init>(FDP.java:27)
	at gr.uom.java.jdeodorant.refactoring.views.MetricsAction$1.run(MetricsAction.java:141)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by preetisaini** [comment]
Fixed and Committed.
